### ISSUE TITLE
Error during installation of particle dev local compiler

### ISSUE THREAD

**Issue by afassio** [spark/particle-dev-local-compiler#33]
Try to install local compiler for particle dev but have this error:.

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Win10
**Thrown From**: [particle-dev-local-compiler](https://github.com/spark/particle-dev-local-compiler) package 0.1.2

### Stack Trace

Failed to activate the particle-dev-local-compiler package

```
At spawnSync undefined ENOENT

Error: spawnSync undefined ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:480:20)
    at Object.execFileSync (child_process.js:517:13)
    at Object.module.(anonymous function) [as execFileSync] (ELECTRON_ASAR.js:173:20)
    at Object.setupDocker (/packages/particle-dev-local-compiler/lib/main.coffee:101:35)
    at Object.activate (/packages/particle-dev-local-compiler/lib/main.coffee:31:4)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.3/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.3/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.19.3/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.19.3/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
console-panel 0.2.1 
file-icons 2.1.11 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.7 
minimap 4.29.6 
particle-dev 0.1.24 
particle-dev-cloud-functions 0.1.2 
particle-dev-cloud-variables 0.1.2 
particle-dev-complete 1.0.2 
particle-dev-libraries 0.2.21 
particle-dev-profiles 0.2.2 
particle-dev-release-notes 0.53.2 
platformio-ide 2.0.0-beta.8 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.5.5 
tool-bar 1.1.0 
```

**Comment by suda** [comment]
Hi @afassio ! We've just released `0.1.3` which should fix this problem on Windows
