### ISSUE TITLE
Installation problem no.2

### ISSUE THREAD

**Issue by afassio** [spark/particle-dev-local-compiler#34]
Hi
still one error. Can you help me?
Error: Command failed: docker-compose -f C:\Users\Alberto.atom\packages\particle-dev-local-compiler\docker-compose.yml up --force-recreate -d Traceback (most recent call last): File "docker-compose", line 3, in File "compose\cli\main.py", line 68, in main File "compose\cli\main.py", line 118, in perform_command File "compose\cli\main.py", line 926, in up File "compose\project.py", line 388, in up File "compose\project.py", line 614, in warn_for_swarm_mode File "site-packages\docker\api\daemon.py", line 90, in info File "site-packages\docker\utils\decorators.py", line 47, in inner File "site-packages\docker\api\client.py", line 183, in _get File "site-packages\requests\sessions.py", line 488, in get File "site-packages\requests\sessions.py", line 475, in request File "site-packages\requests\sessions.py", line 596, in send File "site-packages\requests\adapters.py", line 423, in send File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request File "httplib.py", line 1042, in request File "httplib.py", line 1082, in _send_request File "httplib.py", line 1038, in endheaders File "httplib.py", line 882, in _send_output File "httplib.py", line 844, in send File "site-packages\docker\transport\npipeconn.py", line 31, in connect File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped File "site-packages\docker\transport\npipesocket.py", line 50, in connect pywintypes.error: (2, 'WaitNamedPipe', 'Impossibile trovare il file specificato.') Failed to execute script docker-compose

**Comment by suda** [comment]
Oh interesting. It looks like `docker-compose` command failed. I'm seeing something about `warn_for_swarm_mode`... 🤔  What happens when you execute following command in `cmd` or `PowerShell`:

```
docker-compose -f C:\Users\Alberto.atom\packages\particle-dev-local-compiler\docker-compose.yml up --force-recreate
```

**Comment by afassio** [comment]
I have installed docker toolbox because Docker does not work on my 64bit PC (Win 10 Home not professional)
I test docker-compose launching in bash and it works

**Comment by afassio** [comment]
Sorry for close the issue

**Comment by afassio** [comment]
Test in powershell and it does not work. But it is clear, docker is not working as a service.
If I launch the string after Docker toolbox on , it works in bash windows

**Comment by suda** [comment]
Oh, it's useful to know Docker for Win doesn't work with Home edition (which is a shame because that's probably what most of people have). We don't support Docker Toolbox anymore but it seems it should be added again.

I think the reason it doesn't work in PowerShell is lack of env variables. In Bash, what's the output of `printenv | grep docker`?

Also in PS, when you just run `docker-compose` what's the output?

**Comment by afassio** [comment]
The output in powershell is (running in .atom/packages/particle-dev-local-compiler

Traceback (most recent call last): File "docker-compose", line 3, in File "compose\cli\main.py", line 68, in main File "compose\cli\main.py", line 118, in perform_command File "compose\cli\main.py", line 926, in up File "compose\project.py", line 388, in up File "compose\project.py", line 614, in warn_for_swarm_mode File "site-packages\docker\api\daemon.py", line 90, in info File "site-packages\docker\utils\decorators.py", line 47, in inner File "site-packages\docker\api\client.py", line 183, in _get File "site-packages\requests\sessions.py", line 488, in get File "site-packages\requests\sessions.py", line 475, in request File "site-packages\requests\sessions.py", line 596, in send File "site-packages\requests\adapters.py", line 423, in send File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request File "httplib.py", line 1042, in request File "httplib.py", line 1082, in _send_request File "httplib.py", line 1038, in endheaders File "httplib.py", line 882, in _send_output File "httplib.py", line 844, in send File "site-packages\docker\transport\npipeconn.py", line 31, in connect File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped File "site-packages\docker\transport\npipesocket.py", line 50, in connect pywintypes.error: (2, 'WaitNamedPipe', 'Impossibile trovare il file specificato.') Failed to execute script docker-compose

if I run in a different directory the command fails

**Comment by afassio** [comment]
printenv | grep docker results:

docker_cert_path=c:\users\alberto\.docker\machine\machines\default
Bash_func_docker%%=() {  MSYS_NO_PATHCONV=1 docker.exe "$@"

**Comment by afassio** [comment]
Think the problem is not docker...

**Comment by suda** [comment]
Hmmm if `docker-compose` doesn't work at all in PowerShell but it does in Bash then I would say it's the same reason why this package is failing. If you would be able to make it work in PS and let us know how you achieved it that would be great!

**Comment by afassio** [comment]
I try to solve but I need more info.
Where are locatef the py files invocked by docker compose?

**Comment by afassio** [comment]
find solution for powershell
in powershell if I launch the following commands, it works
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.99.100:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\Alberto\.docker\machine\machines\default"
$Env:DOCKER_MACHINE_NAME = "default"
$Env:COMPOSE_CONVERT_WINDOWS_PATHS = "true"
& "c:\bin\docker-machine.exe" env default | Invoke-Expression

But even with virtual machine launched and powershell ok, the error above remain.

**Comment by afassio** [comment]
Problem solved.
The issue was that Atom has to be started in powershell where docker machine is on.
So:
1) start docker (with Windows 10 Home) with Docker Quickstart Terminal
2) open PS and launch the command above
3 IN PS launch Atom and install the package.
Now it works
