### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by gruenwaldi** [spark/particle-dev-local-compiler#37]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Ubuntu 16.04.4
**Thrown From**: [particle-dev-local-compiler](https://github.com/spark/particle-dev-local-compiler) package 0.1.3

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///snap/atom/156/usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports.DockerManager.drayLogParser (/packages/particle-dev-local-compiler/lib/docker-manager.coffee:76:17)
    at strData.split.forEach.str (/packages/particle-dev-local-compiler/node_modules/docker-compose-tool/dist/src/main.js:140:44)
    at Array.forEach (native)
    at Socket.onData (/packages/particle-dev-local-compiler/node_modules/docker-compose-tool/dist/src/main.js:140:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Commands

```
     -1:47.1.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always)
     -1:47.1.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -1:46.5.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:46.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:46.4.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:46.4.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:24.9.0 particle-dev:select-device (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:22 particle-dev:update-core-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.9.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.9.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.1.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.1.0 particle-dev-local-compiler:compile-locally (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:50.3.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
console-panel 0.3.0 
file-icons 2.1.21 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
particle-dev 0.2.2 
particle-dev-cloud-functions 0.2.0 
particle-dev-cloud-variables 0.2.0 
particle-dev-complete 1.0.2 
particle-dev-libraries 0.2.30 
particle-dev-local-compiler 0.1.3 
particle-dev-profiles 0.2.3 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
```

**Comment by pigubaoza** [comment]
having the same problem Mac OS 10.13.6
